<?php

namespace Database\Seeders;

use App\Models\Teacher;
use Illuminate\Database\Seeder;

class TeacherSeeder extends Seeder
{
    public function run(): void
    {
        $teachers = [
            ['teacher_id' => 1, 'first_name' => 'Paul', 'last_name' => 'Aigner', 'kuerzel' => 'AP', 'classes' => []],
            ['teacher_id' => 2, 'first_name' => 'Jürgen', 'last_name' => 'Altermüller', 'kuerzel' => 'AL', 'classes' => ['3AHIT']],
            ['teacher_id' => 3, 'first_name' => 'Jakob', 'last_name' => 'Anger', 'kuerzel' => 'AJ', 'classes' => []],
            ['teacher_id' => 4, 'first_name' => 'Simone', 'last_name' => 'Atteneder', 'kuerzel' => 'AT', 'classes' => ['3AHMBA']],
            ['teacher_id' => 5, 'first_name' => 'Alois', 'last_name' => 'Bauer', 'kuerzel' => 'BA', 'classes' => []],
            ['teacher_id' => 6, 'first_name' => 'Christian', 'last_name' => 'Benatzky', 'kuerzel' => 'BC', 'classes' => ['4AHMBA']],
            ['teacher_id' => 7, 'first_name' => 'Christoph', 'last_name' => 'Berger', 'kuerzel' => 'BG', 'classes' => []],
            ['teacher_id' => 8, 'first_name' => 'Robert', 'last_name' => 'Beyer', 'kuerzel' => 'BR', 'classes' => []],
            ['teacher_id' => 9, 'first_name' => 'Christoph', 'last_name' => 'Brandner', 'kuerzel' => 'BN', 'classes' => []],
            ['teacher_id' => 10, 'first_name' => 'Daniel', 'last_name' => 'Brandstetter', 'kuerzel' => 'BD', 'classes' => ['2BHMBA']],
            ['teacher_id' => 11, 'first_name' => 'Alexander', 'last_name' => 'Buchner', 'kuerzel' => 'BU', 'classes' => []],
            ['teacher_id' => 12, 'first_name' => 'Horst', 'last_name' => 'Dietrich', 'kuerzel' => 'DT', 'classes' => []],
            ['teacher_id' => 13, 'first_name' => 'Hannes', 'last_name' => 'Dirnberger', 'kuerzel' => 'DH', 'classes' => ['3BHWIM']],
            ['teacher_id' => 14, 'first_name' => 'Roland', 'last_name' => 'Dobrovits', 'kuerzel' => 'DR', 'classes' => []],
            ['teacher_id' => 15, 'first_name' => 'Bettina', 'last_name' => 'Edlinger', 'kuerzel' => 'EB', 'classes' => []],
            ['teacher_id' => 16, 'first_name' => 'Manuel', 'last_name' => 'Engleder', 'kuerzel' => 'EM', 'classes' => []],
            ['teacher_id' => 17, 'first_name' => 'Heinz', 'last_name' => 'Fangmeyer', 'kuerzel' => 'FA', 'classes' => []],
            ['teacher_id' => 18, 'first_name' => 'Iris', 'last_name' => 'Fischhuber', 'kuerzel' => 'FI', 'classes' => []],
            ['teacher_id' => 19, 'first_name' => 'Markus', 'last_name' => 'Forster', 'kuerzel' => 'FO', 'classes' => ['2AHET']],
            ['teacher_id' => 20, 'first_name' => 'Nikolaus', 'last_name' => 'Frühwirth', 'kuerzel' => 'FN', 'classes' => []],
            ['teacher_id' => 21, 'first_name' => 'Robert', 'last_name' => 'Fuchs', 'kuerzel' => 'FS', 'classes' => []],
            ['teacher_id' => 22, 'first_name' => 'Marie', 'last_name' => 'Fürst', 'kuerzel' => 'FM', 'classes' => []],
            ['teacher_id' => 23, 'first_name' => 'Michael', 'last_name' => 'Galhuber', 'kuerzel' => 'GH', 'classes' => []],
            ['teacher_id' => 24, 'first_name' => 'Roland', 'last_name' => 'Ganzenmüller', 'kuerzel' => 'GN', 'classes' => []],
            ['teacher_id' => 25, 'first_name' => 'Michael', 'last_name' => 'Grabenschweiger', 'kuerzel' => 'GM', 'classes' => []],
            ['teacher_id' => 26, 'first_name' => 'Alexander', 'last_name' => 'Greil', 'kuerzel' => 'GA', 'classes' => ['1AHIT']],
            ['teacher_id' => 27, 'first_name' => 'Bianca', 'last_name' => 'Greil', 'kuerzel' => 'GB', 'classes' => []],
            ['teacher_id' => 28, 'first_name' => 'Alexander', 'last_name' => 'Grosser', 'kuerzel' => 'GR', 'classes' => ['3AHWIM']],
            ['teacher_id' => 29, 'first_name' => 'Günther', 'last_name' => 'Haidbauer', 'kuerzel' => 'HR', 'classes' => ['5BHMBA']],
            ['teacher_id' => 30, 'first_name' => 'Martin', 'last_name' => 'Haider', 'kuerzel' => 'HD', 'classes' => []],
            ['teacher_id' => 31, 'first_name' => 'Simon', 'last_name' => 'Halbertschlager', 'kuerzel' => 'HB', 'classes' => ['1BHMBA']],
            ['teacher_id' => 32, 'first_name' => 'Helene', 'last_name' => 'Haiden', 'kuerzel' => 'HH', 'classes' => []],
            ['teacher_id' => 33, 'first_name' => 'Mathias', 'last_name' => 'Heschl', 'kuerzel' => 'HS', 'classes' => ['1AHWIM']],
            ['teacher_id' => 34, 'first_name' => 'Alexander', 'last_name' => 'Hochbichler', 'kuerzel' => 'HX', 'classes' => ['1BHWIM']],
            ['teacher_id' => 35, 'first_name' => 'Leopold', 'last_name' => 'Hochrieser', 'kuerzel' => 'HO', 'classes' => ['1AFME']],
            ['teacher_id' => 36, 'first_name' => 'Magdalena', 'last_name' => 'Illek', 'kuerzel' => 'IM', 'classes' => ['2AHMBA']],
            ['teacher_id' => 37, 'first_name' => 'Christian', 'last_name' => 'Jandl', 'kuerzel' => 'JC', 'classes' => []],
            ['teacher_id' => 38, 'first_name' => 'Wilhelm', 'last_name' => 'Junker', 'kuerzel' => 'JW', 'classes' => []],
            ['teacher_id' => 39, 'first_name' => 'Richard', 'last_name' => 'Kickinger', 'kuerzel' => 'KR', 'classes' => []],
            ['teacher_id' => 40, 'first_name' => 'Medine', 'last_name' => 'Kisa', 'kuerzel' => 'KM', 'classes' => []],
            ['teacher_id' => 41, 'first_name' => 'Johannes', 'last_name' => 'Kittinger', 'kuerzel' => 'KI', 'classes' => ['4AFME']],
            ['teacher_id' => 42, 'first_name' => 'Tobias', 'last_name' => 'Kletecka', 'kuerzel' => 'TK', 'classes' => []],
            ['teacher_id' => 43, 'first_name' => 'Johann', 'last_name' => 'Köberl', 'kuerzel' => 'KO', 'classes' => []],
            ['teacher_id' => 44, 'first_name' => 'Josef', 'last_name' => 'Kogler', 'kuerzel' => 'JK', 'classes' => []],
            ['teacher_id' => 45, 'first_name' => 'Bianca', 'last_name' => 'Kölbel', 'kuerzel' => 'KB', 'classes' => ['1AHET']],
            ['teacher_id' => 46, 'first_name' => 'Siegfried', 'last_name' => 'Kolck-Thudt', 'kuerzel' => 'KD', 'classes' => []],
            ['teacher_id' => 47, 'first_name' => 'Christian', 'last_name' => 'Koller', 'kuerzel' => 'KC', 'classes' => []],
            ['teacher_id' => 48, 'first_name' => 'Thomas', 'last_name' => 'Krahofer', 'kuerzel' => 'KT', 'classes' => []],
            ['teacher_id' => 49, 'first_name' => 'Jürgen', 'last_name' => 'Krajsek-Pilz', 'kuerzel' => 'KJ', 'classes' => ['4BHWIM']],
            ['teacher_id' => 50, 'first_name' => 'Georg', 'last_name' => 'Kromoser', 'kuerzel' => 'KG', 'classes' => ['3BHMBA']],
            ['teacher_id' => 51, 'first_name' => 'Iva', 'last_name' => 'Kronister', 'kuerzel' => 'IK', 'classes' => ['2AHIT']],
            ['teacher_id' => 52, 'first_name' => 'Tamara', 'last_name' => 'Kupfer', 'kuerzel' => 'KU', 'classes' => []],
            ['teacher_id' => 53, 'first_name' => 'Josef', 'last_name' => 'Leichtfried', 'kuerzel' => 'LF', 'classes' => []],
            ['teacher_id' => 54, 'first_name' => 'Gerhard', 'last_name' => 'Marchard', 'kuerzel' => 'MG', 'classes' => []],
            ['teacher_id' => 55, 'first_name' => 'Markus', 'last_name' => 'Maurer', 'kuerzel' => 'MM', 'classes' => []],
            ['teacher_id' => 56, 'first_name' => 'Josef', 'last_name' => 'Merkinger', 'kuerzel' => 'ME', 'classes' => []],
            ['teacher_id' => 57, 'first_name' => 'Gernot', 'last_name' => 'Mevec', 'kuerzel' => 'MV', 'classes' => []],
            ['teacher_id' => 58, 'first_name' => 'Ewald', 'last_name' => 'Nowak', 'kuerzel' => 'NO', 'classes' => []],
            ['teacher_id' => 59, 'first_name' => 'Markus', 'last_name' => 'Oberklammer', 'kuerzel' => 'OM', 'classes' => []],
            ['teacher_id' => 60, 'first_name' => 'Stefan', 'last_name' => 'Pechhacker', 'kuerzel' => 'PS', 'classes' => []],
            ['teacher_id' => 61, 'first_name' => 'Juraj', 'last_name' => 'Petko', 'kuerzel' => 'PJ', 'classes' => []],
            ['teacher_id' => 62, 'first_name' => 'Erich', 'last_name' => 'Pilsinger', 'kuerzel' => 'PE', 'classes' => []],
            ['teacher_id' => 63, 'first_name' => 'Thomas', 'last_name' => 'Pilz', 'kuerzel' => 'PT', 'classes' => []],
            ['teacher_id' => 64, 'first_name' => 'Othmar', 'last_name' => 'Pöschl', 'kuerzel' => 'PO', 'classes' => []],
            ['teacher_id' => 65, 'first_name' => 'Philipp', 'last_name' => 'Punzengruber', 'kuerzel' => 'PP', 'classes' => []],
            ['teacher_id' => 66, 'first_name' => 'Martin', 'last_name' => 'Raab', 'kuerzel' => 'RA', 'classes' => ['4AHWIM']],
            ['teacher_id' => 67, 'first_name' => 'Tobias', 'last_name' => 'Ritt', 'kuerzel' => 'RO', 'classes' => ['2AHWIM']],
            ['teacher_id' => 68, 'first_name' => 'Maria', 'last_name' => 'Rittmannsberger', 'kuerzel' => 'RI', 'classes' => ['5AHET']],
            ['teacher_id' => 69, 'first_name' => 'Konrad', 'last_name' => 'Rumetshofer', 'kuerzel' => 'RU', 'classes' => []],
            ['teacher_id' => 70, 'first_name' => 'Andreas', 'last_name' => 'Salcher', 'kuerzel' => 'SA', 'classes' => []],
            ['teacher_id' => 71, 'first_name' => 'Christian', 'last_name' => 'Salcher', 'kuerzel' => 'SL', 'classes' => ['5AHIT']],
            ['teacher_id' => 72, 'first_name' => 'Madlene', 'last_name' => 'Salcher', 'kuerzel' => 'SM', 'classes' => ['3AHMBA']],
            ['teacher_id' => 73, 'first_name' => 'Gabriel', 'last_name' => 'Schagerl', 'kuerzel' => 'GS', 'classes' => ['4AHIT']],
            ['teacher_id' => 74, 'first_name' => 'Andreas', 'last_name' => 'Schatz', 'kuerzel' => 'SZ', 'classes' => []],
            ['teacher_id' => 75, 'first_name' => 'Oliver', 'last_name' => 'Schindlegger', 'kuerzel' => 'SI', 'classes' => []],
            ['teacher_id' => 76, 'first_name' => 'Bianca', 'last_name' => 'Schnabler', 'kuerzel' => 'SH', 'classes' => ['3AHET']],
            ['teacher_id' => 77, 'first_name' => 'Joachim', 'last_name' => 'Schneiber', 'kuerzel' => 'SB', 'classes' => []],
            ['teacher_id' => 78, 'first_name' => 'Christian', 'last_name' => 'Schneider', 'kuerzel' => 'SN', 'classes' => ['2AFME']],
            ['teacher_id' => 79, 'first_name' => 'Christina', 'last_name' => 'Schnetzinger', 'kuerzel' => 'SE', 'classes' => []],
            ['teacher_id' => 80, 'first_name' => 'Michaela', 'last_name' => 'Scholler', 'kuerzel' => 'MS', 'classes' => []],
            ['teacher_id' => 81, 'first_name' => 'Wolfgang', 'last_name' => 'Seisenbacher', 'kuerzel' => 'SW', 'classes' => ['3AFME']],
            ['teacher_id' => 82, 'first_name' => 'Martin', 'last_name' => 'Stix', 'kuerzel' => 'SX', 'classes' => []],
            ['teacher_id' => 83, 'first_name' => 'Leopold', 'last_name' => 'Stockinger', 'kuerzel' => 'SO', 'classes' => ['4AHET']],
            ['teacher_id' => 84, 'first_name' => 'Sabrina', 'last_name' => 'Stöckler', 'kuerzel' => 'SK', 'classes' => []],
            ['teacher_id' => 85, 'first_name' => 'Michael', 'last_name' => 'Sturm', 'kuerzel' => 'ST', 'classes' => ['4BHMBA']],
            ['teacher_id' => 86, 'first_name' => 'Manfred', 'last_name' => 'Tiefenböck', 'kuerzel' => 'TB', 'classes' => []],
            ['teacher_id' => 87, 'first_name' => 'Franz', 'last_name' => 'Tojner', 'kuerzel' => 'TO', 'classes' => []],
            ['teacher_id' => 88, 'first_name' => 'Joachim', 'last_name' => 'Wagner', 'kuerzel' => 'WJ', 'classes' => ['5AHMBA']],
            ['teacher_id' => 89, 'first_name' => 'Hubert', 'last_name' => 'Wahlmüller', 'kuerzel' => 'WM', 'classes' => []],
            ['teacher_id' => 90, 'first_name' => 'Birgit', 'last_name' => 'Walterskirchen', 'kuerzel' => 'WK', 'classes' => []],
            ['teacher_id' => 91, 'first_name' => 'Klaus', 'last_name' => 'Weichinger', 'kuerzel' => 'WG', 'classes' => ['2AAME']],
            ['teacher_id' => 92, 'first_name' => 'Robert', 'last_name' => 'Wildpert', 'kuerzel' => 'WR', 'classes' => ['5BHWIM']],
            ['teacher_id' => 93, 'first_name' => 'Angela', 'last_name' => 'Winkelhofer', 'kuerzel' => 'WI', 'classes' => ['1AHMBA']],
            ['teacher_id' => 94, 'first_name' => 'David', 'last_name' => 'Zambal', 'kuerzel' => 'ZD', 'classes' => ['5AHWIM']],
            ['teacher_id' => 95, 'first_name' => 'Sebastian', 'last_name' => 'Zambal', 'kuerzel' => 'ZS', 'classes' => []],
            ['teacher_id' => 96, 'first_name' => 'Christoph', 'last_name' => 'Zeillinger', 'kuerzel' => 'ZE', 'classes' => ['2BHWIM']],
        ];

        foreach ($teachers as $teacherData) {
            Teacher::updateOrCreate(
                ['teacher_id' => $teacherData['teacher_id']],
                $teacherData
            );
        }
    }
}
